/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryPlanIdRouteImport } from './routes/history_.$planId'
import { Route as PlannerHomeRouteImport } from './routes/planner.home'
import { Route as PlannerJewelryRouteImport } from './routes/planner.jewelry'
import { Route as PlannerPartyRouteImport } from './routes/planner.party'
import { Route as PlannerHomeResultsPlanIdRouteImport } from './routes/planner.home_.results.$planId'
import { Route as PlannerJewelryResultsPlanIdRouteImport } from './routes/planner.jewelry_.results.$planId'
import { Route as PlannerPartyResultsPlanIdRouteImport } from './routes/planner.party_.results.$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryPlanIdRoute = HistoryPlanIdRouteImport.update({
  id: '/history_/$planId',
  path: '/history/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerHomeRoute = PlannerHomeRouteImport.update({
  id: '/planner/home',
  path: '/planner/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerJewelryRoute = PlannerJewelryRouteImport.update({
  id: '/planner/jewelry',
  path: '/planner/jewelry',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerPartyRoute = PlannerPartyRouteImport.update({
  id: '/planner/party',
  path: '/planner/party',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerHomeResultsPlanIdRoute =
  PlannerHomeResultsPlanIdRouteImport.update({
    id: '/planner/home_/results/$planId',
    path: '/planner/home/results/$planId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlannerJewelryResultsPlanIdRoute =
  PlannerJewelryResultsPlanIdRouteImport.update({
    id: '/planner/jewelry_/results/$planId',
    path: '/planner/jewelry/results/$planId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlannerPartyResultsPlanIdRoute =
  PlannerPartyResultsPlanIdRouteImport.update({
    id: '/planner/party_/results/$planId',
    path: '/planner/party/results/$planId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/history/$planId': typeof HistoryPlanIdRoute
  '/planner/home': typeof PlannerHomeRoute
  '/planner/jewelry': typeof PlannerJewelryRoute
  '/planner/party': typeof PlannerPartyRoute
  '/planner/home/results/$planId': typeof PlannerHomeResultsPlanIdRoute
  '/planner/jewelry/results/$planId': typeof PlannerJewelryResultsPlanIdRoute
  '/planner/party/results/$planId': typeof PlannerPartyResultsPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/history/$planId': typeof HistoryPlanIdRoute
  '/planner/home': typeof PlannerHomeRoute
  '/planner/jewelry': typeof PlannerJewelryRoute
  '/planner/party': typeof PlannerPartyRoute
  '/planner/home/results/$planId': typeof PlannerHomeResultsPlanIdRoute
  '/planner/jewelry/results/$planId': typeof PlannerJewelryResultsPlanIdRoute
  '/planner/party/results/$planId': typeof PlannerPartyResultsPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/history_/$planId': typeof HistoryPlanIdRoute
  '/planner/home': typeof PlannerHomeRoute
  '/planner/jewelry': typeof PlannerJewelryRoute
  '/planner/party': typeof PlannerPartyRoute
  '/planner/home_/results/$planId': typeof PlannerHomeResultsPlanIdRoute
  '/planner/jewelry_/results/$planId': typeof PlannerJewelryResultsPlanIdRoute
  '/planner/party_/results/$planId': typeof PlannerPartyResultsPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/history/$planId'
    | '/planner/home'
    | '/planner/jewelry'
    | '/planner/party'
    | '/planner/home/results/$planId'
    | '/planner/jewelry/results/$planId'
    | '/planner/party/results/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/history/$planId'
    | '/planner/home'
    | '/planner/jewelry'
    | '/planner/party'
    | '/planner/home/results/$planId'
    | '/planner/jewelry/results/$planId'
    | '/planner/party/results/$planId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/history_/$planId'
    | '/planner/home'
    | '/planner/jewelry'
    | '/planner/party'
    | '/planner/home_/results/$planId'
    | '/planner/jewelry_/results/$planId'
    | '/planner/party_/results/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  HistoryPlanIdRoute: typeof HistoryPlanIdRoute
  PlannerHomeRoute: typeof PlannerHomeRoute
  PlannerJewelryRoute: typeof PlannerJewelryRoute
  PlannerPartyRoute: typeof PlannerPartyRoute
  PlannerHomeResultsPlanIdRoute: typeof PlannerHomeResultsPlanIdRoute
  PlannerJewelryResultsPlanIdRoute: typeof PlannerJewelryResultsPlanIdRoute
  PlannerPartyResultsPlanIdRoute: typeof PlannerPartyResultsPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$planId': {
      id: '/history_/$planId'
      path: '/history/$planId'
      fullPath: '/history/$planId'
      preLoaderRoute: typeof HistoryPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/home': {
      id: '/planner/home'
      path: '/planner/home'
      fullPath: '/planner/home'
      preLoaderRoute: typeof PlannerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/jewelry': {
      id: '/planner/jewelry'
      path: '/planner/jewelry'
      fullPath: '/planner/jewelry'
      preLoaderRoute: typeof PlannerJewelryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/party': {
      id: '/planner/party'
      path: '/planner/party'
      fullPath: '/planner/party'
      preLoaderRoute: typeof PlannerPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/home_/results/$planId': {
      id: '/planner/home_/results/$planId'
      path: '/planner/home/results/$planId'
      fullPath: '/planner/home/results/$planId'
      preLoaderRoute: typeof PlannerHomeResultsPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/jewelry_/results/$planId': {
      id: '/planner/jewelry_/results/$planId'
      path: '/planner/jewelry/results/$planId'
      fullPath: '/planner/jewelry/results/$planId'
      preLoaderRoute: typeof PlannerJewelryResultsPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/party_/results/$planId': {
      id: '/planner/party_/results/$planId'
      path: '/planner/party/results/$planId'
      fullPath: '/planner/party/results/$planId'
      preLoaderRoute: typeof PlannerPartyResultsPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  HistoryPlanIdRoute: HistoryPlanIdRoute,
  PlannerHomeRoute: PlannerHomeRoute,
  PlannerJewelryRoute: PlannerJewelryRoute,
  PlannerPartyRoute: PlannerPartyRoute,
  PlannerHomeResultsPlanIdRoute: PlannerHomeResultsPlanIdRoute,
  PlannerJewelryResultsPlanIdRoute: PlannerJewelryResultsPlanIdRoute,
  PlannerPartyResultsPlanIdRoute: PlannerPartyResultsPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
